version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: voiture_user
      MYSQL_PASSWORD: voiture_user_password
      MYSQL_DATABASE: voiture

  spring-boot-app:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/voiture
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: P@ssw0rd

  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:80"
